config/routes.rb
Rails.application.routes.draw do
  resources :transactions, only: %i[ index new create edit update destroy ]
  devise_for :users
  root to: "home#index"
  get "balance_sheet", to: "transactions#balance_sheet", as: "balance_sheet"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user

  enum transaction_type: [ :Expense, :Enter ]

  validates :transaction_type, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  has_many :transactions, dependent: :destroy

  validates :name, presence: true, length: { maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [ :name ])
        devise_parameter_sanitizer.permit(:account_update, keys: [ :name ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transaction, only: %i[ edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.where(user: current_user).order(created_at: :desc)
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    @transaction.user_id = current_user.id

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_url, notice: "Transaction was successfully created." }
        format.json { render :index, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transactions_url, notice: "Transaction was successfully updated." }
        format.json { render :index, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def balance_sheet
    @total_expenses = Transaction.where(user: current_user).where(transaction_type: 0).sum(:amount)
    @total_entries = Transaction.where(user: current_user).where(transaction_type: 1).sum(:amount)
    @reserve = @total_entries - @total_expenses
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:transaction_type, :amount, :transaction_date, :motif)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/home/index.html.erb
<div class="page-header section-dark" style="background-image: url('http://demos.creative-tim.com/paper-kit-2/assets/img/antoine-barres.jpg')">
    <div class="filter"></div>
    <div class="content-center">
        <div class="container">
            <div class="title-brand">
                <h1 class="presentation-title">EXPENSES MANAGER</h1>
                <div class="fog-low">
                    <img src="http://demos.creative-tim.com/paper-kit-2/assets/img/fog-low.png" alt="">
                </div>
                <div class="fog-low right">
                    <img src="http://demos.creative-tim.com/paper-kit-2/assets/img/fog-low.png" alt="">
                </div>
            </div>
        </div>
    </div>
    <div class="moving-clouds" style="background-image: url('http://demos.creative-tim.com/paper-kit-2/assets/img/clouds.png'); ">

    </div>
</div>


<script>
    var searchVisible = 0;
    var transparent = true;

    var transparentDemo = true;
    var fixedTop = false;

    var navbar_initialized = false;

    $(document).ready(function(){
        window_width = $(window).width();

        //  Activate the tooltips
        $('[data-toggle="tooltip"]').tooltip();

        //      Activate the switches with icons
        if($('.switch').length != 0){
            $('.switch')['bootstrapSwitch']();
        }
        //      Activate regular switches
        if($("[data-toggle='switch']").length != 0){
            $("[data-toggle='switch']").bootstrapSwitch();
        }

        if($(".tagsinput").length != 0){
            $(".tagsinput").tagsInput();
        }
        if (window_width >= 768) {
            big_image = $('.page-header[data-parallax="true"]');

            if(big_image.length != 0){
            $(window).on('scroll', pk.checkScrollForPresentationPage);
            }
        }

        if($("#datetimepicker").length != 0){
            $('#datetimepicker').datetimepicker({
                icons: {
                    time: "fa fa-clock-o",
                    date: "fa fa-calendar",
                    up: "fa fa-chevron-up",
                    down: "fa fa-chevron-down",
                    previous: 'fa fa-chevron-left',
                    next: 'fa fa-chevron-right',
                    today: 'fa fa-screenshot',
                    clear: 'fa fa-trash',
                    close: 'fa fa-remove'
                },
                debug: true
            });
        };

        // Navbar color change on scroll
        if($('.navbar[color-on-scroll]').length != 0){
            $(window).on('scroll', pk.checkScrollForTransparentNavbar)
        }


        $('.btn-tooltip').tooltip();
        $('.label-tooltip').tooltip();

        // Carousel
        $('.carousel').carousel({
        interval: 4000
        });

        $('.form-control').on("focus", function(){
            $(this).parent('.input-group').addClass("input-group-focus");
        }).on("blur", function(){
            $(this).parent(".input-group").removeClass("input-group-focus");
        });

        // Init popovers
        pk.initPopovers();

        // Init Collapse Areas
        pk.initCollapseArea();

        // Init Sliders
        pk.initSliders();

    });


    $(document).on('click', '.navbar-toggler', function(){
        $toggle = $(this);
        if(pk.misc.navbar_menu_visible == 1) {
            $('html').removeClass('nav-open');
            pk.misc.navbar_menu_visible = 0;
            setTimeout(function(){
                $toggle.removeClass('toggled');
                $('#bodyClick').remove();
            }, 550);
        } else {
            setTimeout(function(){
                $toggle.addClass('toggled');
            }, 580);

            div = '<div id="bodyClick"></div>';
            $(div).appendTo("body").click(function() {
                $('html').removeClass('nav-open');
                pk.misc.navbar_menu_visible = 0;
                $('#bodyClick').remove();
                setTimeout(function(){
                    $toggle.removeClass('toggled');
                }, 550);
            });

            $('html').addClass('nav-open');
            pk.misc.navbar_menu_visible = 1;
        }
    });

    pk = {
        misc:{
            navbar_menu_visible: 0
        },

        checkScrollForPresentationPage: debounce(function(){
            oVal = ($(window).scrollTop() / 3);
            big_image.css({
                'transform':'translate3d(0,' + oVal +'px,0)',
                '-webkit-transform':'translate3d(0,' + oVal +'px,0)',
                '-ms-transform':'translate3d(0,' + oVal +'px,0)',
                '-o-transform':'translate3d(0,' + oVal +'px,0)'
            });
        }, 4),

        checkScrollForTransparentNavbar: debounce(function() {
                if($(document).scrollTop() > $(".navbar").attr("color-on-scroll") ) {
                    if(transparent) {
                        transparent = false;
                        $('.navbar[color-on-scroll]').removeClass('navbar-transparent');
                    }
                } else {
                    if( !transparent ) {
                        transparent = true;
                        $('.navbar[color-on-scroll]').addClass('navbar-transparent');
                    }
                }
        }, 17),

        initPopovers: function(){
            if($('[data-toggle="popover"]').length != 0){
                $('body').append('<div class="popover-filter"></div>');

                //    Activate Popovers
            $('[data-toggle="popover"]').popover().on('show.bs.popover', function () {
                    $('.popover-filter').click(function(){
                        $(this).removeClass('in');
                        $('[data-toggle="popover"]').popover('hide');
                    });
                    $('.popover-filter').addClass('in');
                }).on('hide.bs.popover', function(){
                    $('.popover-filter').removeClass('in');
                });

            }
        },
        initCollapseArea: function(){
            $('[data-toggle="pk-collapse"]').each(function () {
                var thisdiv = $(this).attr("data-target");
                $(thisdiv).addClass("pk-collapse");
            });

            $('[data-toggle="pk-collapse"]').hover(function(){
                var thisdiv = $(this).attr("data-target");
                if(!$(this).hasClass('state-open')){
                    $(this).addClass('state-hover');
                    $(thisdiv).css({
                        'height':'30px'
                    });
                }

            },
            function(){
                var thisdiv = $(this).attr("data-target");
                $(this).removeClass('state-hover');

                if(!$(this).hasClass('state-open')){
                    $(thisdiv).css({
                        'height':'0px'
                    });
                }
            }).click(function(event){
                    event.preventDefault();

                    var thisdiv = $(this).attr("data-target");
                    var height = $(thisdiv).children('.panel-body').height();

                    if($(this).hasClass('state-open')){
                        $(thisdiv).css({
                            'height':'0px',
                        });
                        $(this).removeClass('state-open');
                    } else {
                        $(thisdiv).css({
                            'height':height + 30,
                        });
                        $(this).addClass('state-open');
                    }
                });
        },
        initSliders: function(){
            // Sliders for demo purpose in refine cards section
            if($('#sliderRegular').length != 0 ){
                var rangeSlider = document.getElementById('sliderRegular');
                noUiSlider.create(rangeSlider, {
                    start: [ 5000 ],
                    range: {
                        'min': [  2000 ],
                        'max': [ 10000 ]
                    }
                });
            }
            if($('#sliderDouble').length != 0){
                var slider = document.getElementById('sliderDouble');
                noUiSlider.create(slider, {
                    start: [20, 80],
                    connect: true,
                    range: {
                        'min': 0,
                        'max': 100
                    }
                });
            }

        },


    }

    examples = {
        initContactUsMap: function(){
            var myLatlng = new google.maps.LatLng(44.433530, 26.093928);
            var mapOptions = {
            zoom: 14,
            center: myLatlng,
            scrollwheel: false, //we disable de scroll over the map, it is a really annoing when you scroll through page
            }
            var map = new google.maps.Map(document.getElementById("contactUsMap"), mapOptions);

            var marker = new google.maps.Marker({
                position: myLatlng,
                title:"Hello World!"
            });

            // To add the marker to the map, call setMap();
            marker.setMap(map);
            }
    }

    // Returns a function, that, as long as it continues to be invoked, will not
    // be triggered. The function will be called after it stops being called for
    // N milliseconds. If `immediate` is passed, trigger the function on the
    // leading edge, instead of the trailing.

    function debounce(func, wait, immediate) {
        var timeout;
        return function() {
            var context = this, args = arguments;
            clearTimeout(timeout);
            timeout = setTimeout(function() {
                timeout = null;
                if (!immediate) func.apply(context, args);
            }, wait);
            if (immediate && !timeout) func.apply(context, args);
        };
    };

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expense Manager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'sweetalert.min.js' %>
    <%= yield :head %>
  </head>

  <body>
  
    <div id="main">
      <div class="container_menu">
        <nav>
          <div class="nav-fostrap d-flex justify-content-center">
            <ul class="px-md-5">
              <li><%= link_to "Home", root_path %></li>
              <% if current_user %>
                <li><%= link_to "My transactions", transactions_path %></li>
                <li><%= link_to "New transaction", new_transaction_path %></li>
                <li><%= link_to "My balance sheet", balance_sheet_path %></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "Log in", new_user_session_path %></li>
                <li><%= link_to "Sign up", new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
          <div class="nav-bg-fostrap">
            <div class="navbar-fostrap"><span></span> <span></span> <span></span></div>
          </div>
        </nav>
      </div>
    </div>

    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
      </symbol>
      <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
      </symbol>
      <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </symbol>
    </svg>
<!--
    <% if notice %>
      <div class="alert position-fixed alert-success alert-dismissible fade show" role="alert" style="right: 3%;bottom: 4%;z-index: 100;">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <% if alert %>
      <div class="position-fixed alert alert-danger alert-dismissible fade show" role="alert" style="right: 3%;bottom: 4%;z-index: 100;">
        <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
-->
    <% if notice %>
      <script>swal("SUCCESS", "<%= notice %>".split("&#39;").join("'"),"success")</script>
    <% end %>
    <% if alert %>
      <script>swal("WARNING", "<%= alert %>".split("&#39;").join("'"), "warning")</script>
    <% end %>
    <%= yield %>
    <% notice=false %>
    <% alert=false %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function() {
        $('.navbar-fostrap').click(function() {
          $('.nav-fostrap').toggleClass('visible');
          $('#main').toggleClass('cover-bg');
        });
      });
    </script>
  </body>
</html>

app/views/transactions/_form.html.erb
<% content_for :head do %>
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.css">
  <%= stylesheet_link_tag    'login.css' %>
<% end %>

<div style="height: 100vh;" class="container d-flex justify-content-center align-content-center">
  <div class="row">
    <div class="Absolute-Center is-Responsive">
      <div><h2 class="text-center"><%= title %></h2></div>
      <div class="col-sm-12 col-md-10 col-md-offset-1">
        <%= form_with(model: transaction, html: { id: "loginForm" }) do |form| %>

          <div class="form-group">
            <%= form.label :transaction_type %><br>
            <%= form.select :transaction_type, ['Expense', 'Enter'], {class: "form-control"}, {style: "width: 100%;height: 40px;"} %>      
          </div>

          <div class="form-group">
            <%= form.label :amount %><br>
            <%= form.number_field :amount, class: "form-control" %>         
          </div>

          <div class="form-group">
            <%= form.label :date %><br>
            <%= form.date_field :transaction_date, class: "form-control" %>      
          </div>

          <div class="form-group">
            <%= form.label :motif %><br>
            <%= form.text_field :motif, class: "form-control" %>       
          </div>

          <div class="form-group">
            <%= form.submit class: "btn btn-success btn-block" %>
          </div>

        <% end %>        
      </div>  
    </div>    
  </div>
</div>
<%= render "./devise/shared/error_messages", resource: transaction %>

app/views/transactions/balance_sheet.html.erb
<div style="height: 100vh; display: flex; justify-content: center; align-items: center;">
    <div style="width: 400px; height: 400px; text-align: center; box-shadow: 0 16px 30px -12px rgba(0, 0, 0, 0.56), 0 4px 20px 0 rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2); border-radius: 20px;">
        <h2 style="border-bottom: solid 2px rgba(0,0,0,0.1); padding-bottom: 20px;">Balance Sheet</h2><br><br>
        <h3 style="color: green;">Total entries : <%= @total_entries %></h3><br><br>
        <h3 style="color: red;">Total expenses : <%= @total_expenses %></h3><br><br>
        <h3>Reserve : <%= @reserve %></h3>
    </div>
</div>

app/views/transactions/edit.html.erb
<%= render 'form', transaction: @transaction, title: "Editing Transaction" %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<% content_for :head do %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <style>
      thead input {
          width: 100%;
          padding: 3px;
          box-sizing: border-box;
      }
  </style>
<% end %>

<h1 style="margin-top: 100px;" class="mx-5">Transactions</h1>
<div class="p-5">
<table id="example" class="table table-striped table-bordered" cellspacing="0">
    <thead>
        <tr>
            <th><span class="d-flex flex-column align-items-center">Type</span></th>
            <th><span class="d-flex flex-column align-items-center">Amount</span></th>
            <th><span class="d-flex flex-column align-items-center">Date</span></th>
            <th><span class="d-flex flex-column align-items-center">Motif</span></th>
            <th style="text-align:center;min-width: 100px;">
              <%= link_to new_transaction_path, class: "d-flex flex-column align-items-center" do %>
                New transaction
                <button type="button" data-func="dt-add" class="mx-2 btn btn-success btn-xs dt-add">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                </button>
              <% end %>
            </th>
        </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <tr 
          <% if transaction.transaction_type == "Expense" %>
            style="background-color: rgb(253, 231, 231) !important;"
          <% else %>
            style="background-color: rgb(231, 253, 235) !important;"
          <% end %>
        >
            <td><%= transaction.transaction_type %></td>
            <td><%= transaction.amount %></td>
            <td><%= transaction.transaction_date %></td>
            <td><%= transaction.motif %></td>
            <td>
              <%= link_to edit_transaction_path(transaction) do %>
                <button type="button" class="btn btn-primary btn-xs dt-edit" style="margin-right:16px;">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </button>
              <% end %>
              <%= link_to transaction, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <button type="button" class="btn btn-danger btn-xs dt-delete">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                </button>
              <% end %>
            </td>
        </tr>
      <% end %>
    </tbody>
</table>
</div>

app/views/transactions/new.html.erb
<%= render 'form', transaction: @transaction, title: "New Transaction" %>

<%= link_to 'Back', transactions_path %>